### ISSUE TITLE
Incorrect order of coordinates in readme docs

### ISSUE THREAD

**Issue by Guseyn** [mondeja/svg-path-bbox#1]
Hi, first of all thank you for this lib, it works perfectly, but in the readme you write that:
"The bounding box returned is an array made up in the same way of viewBox SVG attributes: `[x0, x1, y0, y1]`."
But in my tests `svgPathBbox(path)` actually returns coordinates in a bit different order: `[x0, y0, x1, x2]`

**Comment by mondeja** [comment]
It's an error in documentation :no_mouth: ... thanks for catch it! :+1:
