### ISSUE TITLE
feature request: does this repo support arc? such as M 1 1 A 2 2 45 1 1 2 3

### ISSUE THREAD

**Issue by zengxiaoluan** [mondeja/svg-path-bbox#107]

**Comment by mondeja** [comment]
Yes, this project support all commands defined in the [SVG v1.1 specification](https://www.w3.org/TR/SVG/paths.html) and [elliptical arc commands (A/a)](https://www.w3.org/TR/SVG/paths.html#PathDataEllipticalArcCommands) are par of it.
