### ISSUE TITLE
Returns invalid bounding box

### ISSUE THREAD

**Issue by casper-k** [mondeja/svg-path-bbox#61]
First of all, thanks for sharing this library. Clean and simple.

Working with your library, I noticed that it doesn't return the correct bounding box with some shapes.

In this case, the returned coordinates are as expected:
`M 22.2076 22.2076 C 22.2076 22.2076 22.2076 22.2076 200.0000 0.0000 200.0000 0.0000 200.0000 0.0000 222.2076 222.2076 222.2076 222.2076 222.2076 222.2076 22.2076 222.2076 22.2076 222.2076 22.2076 222.2076 22.2076 22.2076`
Returns:
`[22.2076, 0, 222.2076, 222.2076]`

![correct](https://user-images.githubusercontent.com/44575638/122583793-e9e99c00-d059-11eb-963d-4d5cd0c4bf41.png)

But this very similar shape returns an invalid bounding box:
`M 21.1456 21.1456 C 21.1456 21.1456 21.1456 21.1456 200.0000 0.0000 200.0000 0.0000 200.0000 0.0000 221.1456 221.1456 221.1456 221.1456 221.1456 221.1456 21.1456 221.1456 21.1456 221.1456 21.1456 221.1456 21.1456 21.1456`
Returns:
`[21.1456, 0, 221.1456, 256]`

![wrong](https://user-images.githubusercontent.com/44575638/122584241-68ded480-d05a-11eb-9d70-2730b71f5e4b.png)

As you can see, the height is invalid.

Some more examples where the returned coordinates are incorrect:

Wrong y1:
`M 3.9600 3.9600 C 3.9600 3.9600 3.9600 3.9600 200.0000 0.0000 200.0000 0.0000 200.0000 0.0000 203.9600 203.9600 203.9600 203.9600 203.9600 203.9600 3.9600 203.9600 3.9600 203.9600 3.9600 203.9600 3.9600 3.9600`
Returns `3.96 0 203.96 256`

Wrong y1:
`M 59.5504 59.5504 C 59.5504 59.5504 59.5504 59.5504 200.0000 0.0000 200.0000 0.0000 200.0000 0.0000 259.5504 259.5504 259.5504 259.5504 259.5504 259.5504 59.5504 259.5504 59.5504 259.5504 59.5504 259.5504 59.5504 59.5504`
Returns `59.550399999999996 0 259.5504 341.3333333333333`

Wrong x0:
`M 58.2684 58.2684 C 58.2684 58.2684 58.2684 58.2684 200.0000 0.0000 200.0000 0.0000 200.0000 0.0000 258.2684 258.2684 258.2684 258.2684 258.2684 258.2684 58.2684 258.2684 58.2684 258.2684 58.2684 258.2684 58.2684 58.2684`
Returns `32 0 258.2684 258.2684`

**Comment by mondeja** [comment]
Why do you think that `y0 = 0` is wrong? Is not the height, is the Y part of the first coordinate of the bounding box.

**Comment by mondeja** [comment]
Just to be sure, could you explain me why the top part of the very similar shape shouldn't reach 0? As I see, the second cubic bézier curve is targeting 0 as Y part of the coordinate in `200.0000 0.0000 200.0000 0.0000`. For all other examples, is the same but for the first cubic bézier.

**Comment by casper-k** [comment]
Y0 should indeed reach 0, so you're right. But the problem is with Y1. As illustrated in the image, the bounding box (red rectangle) returned for the white shape is incorrect in the 2nd picture.

Compare the output of svg-path-bbox:
svgPathBbox("M 21.1456 21.1456 C 21.1456 21.1456 21.1456 21.1456 200.0000 0.0000 200.0000 0.0000 200.0000 0.0000 221.1456 221.1456 221.1456 221.1456 221.1456 221.1456 21.1456 221.1456 21.1456 221.1456 21.1456 221.1456 21.1456 21.1456")
=> **[21.1456, 0, 221.1456, 256]**

With the output of svg-path-bounds (another package on NPM):
getBounds("M 21.1456 21.1456 C 21.1456 21.1456 21.1456 21.1456 200.0000 0.0000 200.0000 0.0000 200.0000 0.0000 221.1456 221.1456 221.1456 221.1456 221.1456 221.1456 21.1456 221.1456 21.1456 221.1456 21.1456 221.1456 21.1456 21.1456")
=> **[21.1456, 0, 221.1456, 221.1456]**

Note the different value Y1.

**Comment by mondeja** [comment]
Thanks for the report. Should be fixed in [v1.0.1](https://github.com/mondeja/svg-path-bbox/releases/tag/v1.0.1). Could you check it?

**Comment by casper-k** [comment]
Awesome, looks good to me. Thanks for fixing.
